spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: abicoding@sandboxc1d91358c9304115be5b7d417af4513c.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "https://chirp.abi-coding.com"
  rate-limit:
    ip:
      apply-limit: true